apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: prod

labels:
  - pairs:
      environment: prod
      app: demo-app
    includeSelectors: true  

images:
  - name: nginx
    newTag: "1.25-alpine"       # prod uses a hardened, minimal image

patches:
  - path: patch-replicas.yaml
  - path: patch-resources.yaml   # prod gets more CPU/mem limits

configMapGenerator:
  - name: demo-app-config
    literals:
      - ENV=production
      - LOG_LEVEL=warn
      - FEATURE_FLAGS=stable