apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# These are the shared base resources every overlay inherits
resources:
  - deployment.yaml
  - service.yaml

# Common labels applied to ALL resources in every overlay
commonLabels:
  managed-by: kustomize
  project: demo